[
    {
        "changed_data": "{\"project_name\": \"\\u6570\\u636e\\u5e73\\u53f0\\u63a2\\u7d22\\u9879\\u76ee\", \"deleted_at\": \"2020-07-03 14:45:00\", \"updated_by\": \"admin\", \"created_at\": \"2020-07-03 14:45:00\", \"updated_at\": \"2020-07-03 14:45:00\", \"created_by\": \"admin\", \"deleted_by\": \"admin\", \"bk_app_code\": \"data\", \"active\": \"0\", \"project_id\": 5, \"description\": \"\\u6570\\u636e\\u5e73\\u53f0\\u63a2\\u7d22\\u9879\\u76ee\"}",
        "change_time": "2020-07-03 14:48:55",
        "primary_key_value": 5,
        "db_name": "bkdata_basic",
        "table_name": "project_info",
        "method": "CREATE"
    }
]